# Generated by Django 5.1.7 on 2025-03-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='none', max_length=255, unique=True),
        ),
    ]
