# Generated by Django 5.2 on 2025-04-06 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Roga and Kopyta', max_length=255)),
                ('description', models.TextField(default='haha')),
                ('city', models.CharField(default='remote')),
                ('address', models.TextField(default='remote')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='sales', max_length=255)),
                ('description', models.TextField(default='need sales')),
                ('salary', models.FloatField(default=42500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
